// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:4db2c4bb-8983-4e7d-8487-9f65693e1982',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'ezip-hosting-mobilehub-2099129926',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1oaclmwqnyket.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"ezip-mobilehub-2099129926-AWSMobileTable","attributes":[{"name":"teamId","type":"S"},{"name":"personId","type":"S"},{"name":"email","type":"S"},{"name":"personName","type":"S"},{"name":"phone","type":"S"}],"indexes":[{"indexName":"personName-index","hashKey":"teamId","rangeKey":"personName"}],"region":"us-east-1","hashKey":"teamId","rangeKey":"personId"},{"tableName":"ezip-mobilehub-2099129926-tasks","attributes":[{"name":"userId","type":"S"},{"name":"taskId","type":"S"},{"name":"category","type":"S"},{"name":"created","type":"N"},{"name":"description","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"userId","rangeKey":"taskId"}],
    'aws_mobile_analytics_app_id': '8db767ea81d541bfaec4253d854d6c6c',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'c78c120d-121c-11e8-b983-1df4d428e0df',
    'aws_project_name': 'ezip-2018-02-15-12-22-10',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'ezip-mobilehub-2099129926',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'ezip-userfiles-mobilehub-2099129926',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_pcf16eFdK',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '5sjsv9n21fj9659q3u5dqsgg0e',
}

export default awsmobile;
